apiVersion: garden.io/v1
kind: Project
name: hello-world

environments:
  - name: dev

providers:
  - name: kubernetes
    context: ${local.env.CONTEXT_NAME}
    namespace: ${local.env.NAMESPACE}
    deploymentRegistry:
      hostname: dockerhub.io
      namespace: xxx

---

kind: Run
type: helm-pod
name: hello-world
source:
  path: ./
spec:
  resource:
    kind: Job
